### ISSUE TITLE
[S2] 대기화면 로직 구현

### ISSUE THREAD

**Issue by sm-amoled** [cau-bootcamp/wehavit#109]
# 작업 설명

대기 화면을 위한 도메인을 구현합니다.

Relates to: #111, #118 

## 할 일

- [x] 카운트 다운 기능 추가
- [x] 카운트 다운 완료시 액션 구현
    - [x] LiveWritingView에서 필요한 데이터 생성
    - [x] LiveWritingView로 강제 이동시키기
- [x] 대기뷰에 입장하기 가능 추가
- [ ] 대기뷰의 다른 친구를 눌러서 Reaction 보내기 기능 추가

## 예상 결과물

1. 대기 화면과 관련된 도메인
2. 간단한 예시 View

**Comment by IamGroooooot** [comment]
다른 친구를 눌러서 Reaction 보내기 기능 빼고는 현재 모두 구현되었습니다.
