### ISSUE TITLE
[fix] 실기기 quick shot 기능 pan gesture 오류

### ISSUE THREAD

**Issue by sm-amoled** [cau-bootcamp/wehavit#193]
실기기에서 동작을 확인할 때
Home View에서 카메라 버튼 누른 뒤 pan gesture로 손가락 누른 채로 드래그 시 pan gesture 부분이 먹통이 되는 현상이 있어, 일단은 터치영역을 보여주는 기능(현재 터치 영역에 대해 amber 색상의 circle 보여주기)을 비활성화를 적용하였음.

home_screen.dart의 393번째 줄~ 에서 setState() 함수 호출 시 발생하는 문제임을 체크하였고, 이후 해결이 필요함.
```
  void updatePanPosition(Point<double> position) {
    // TODO: panPosition update로 현재 touch position을 보여줘야 함
    // print(position);
    // setState(() {
    //   panPosition = position;
    // });
  }
```

<img src="https://github.com/cau-bootcamp/wehavit/assets/39216546/56872d86-3ee2-4a9d-9e3b-7af073cbb31a" width="300">

_Originally posted by @sm-amoled in https://github.com/cau-bootcamp/wehavit/issues/188#issuecomment-1901712264_

**Comment by sm-amoled** [comment]
@IamGroooooot 
기존에 시연영상 촬영하는 시점부터 homeview에서 카메라 기능 사용 시 pan gesture position 인디케이터가 동작하지 않고 있었나요? panUpdate 내에서 callback 함수 호출 > 함수 내에서 setState 함수 호출하니깐 pangesture 자체가 뻗어버리는 문제가 있어서, 구조를 새로 잡아야할 것 같네용..

**Comment by IamGroooooot** [comment]
> @IamGroooooot 
> 
> 기존에 시연영상 촬영하는 시점부터 homeview에서 카메라 기능 사용 시 pan gesture position 인디케이터가 동작하지 않고 있었나요? panUpdate 내에서 callback 함수 호출 > 함수 내에서 setState 함수 호출하니깐 pangesture 자체가 뻗어버리는 문제가 있어서, 구조를 새로 잡아야할 것 같네용..

정확하게 기억이 안나는데 홈뷰에서는 카메라 자체가 잘 동작하지 않았던 것 같아요.
@Tastypotato245 혹시 기억나??

**Comment by Tastypotato245** [comment]
제가 기억하는 부분은, 해당 기능을 홈뷰 피드들에 붙일 때, provider를 단순히 swipe view에서 사용하는 코드를 그대로 복붙해서 새로 생성하지 않았습니다.  그 부분과 연관이 있지 않을까 싶네요
