### ISSUE TITLE
[S17] 친구 리스트 View 작성하기

### ISSUE THREAD

**Issue by Tastypotato245** [cau-bootcamp/wehavit#30]
User Story:  #19 

- 뷰 구성 요소 나누기
- 실제 코드로 구현하기
- 실제 데이터 셋(파이어베이스)과 연결
- (친구 검색 및 추가는 별도로 구현)

**Comment by Tastypotato245** [comment]
![Image](https://github.com/cau-bootcamp/wehavit/assets/63251068/233d6865-fd0e-44f4-937a-8121df2f3b1b)

**Comment by Tastypotato245** [comment]
실제 데이터 셋과 연결하려면 파이어베이스 연동과 로그인이 필요함. 그 부분도 같이 공부해 보겠음

**Comment by Tastypotato245** [comment]
형들에게 리뷰 받고 파이어베이스에 연동시키면서 마무리 될 예정

**Comment by IamGroooooot** [comment]
굳굳!! 수고했어.

아직 보는 중이긴한데 
router 이제 수정 안하고 바로 버튼 추가해서 수 있도록 짜놓았는데 develop branch merge해서 최신 커밋들 적용해볼래?

router 안에 둔 test_page에 직업 중인 위젯으로 이동하은 버튼만 추가하면 돼

관련 PR: https://github.com/cau-bootcamp/wehavit/pull/55

**Comment by Tastypotato245** [comment]
오키 약간 merge하는게 무서워서 내일 물어보면서 해봄 이제 확인.

**Comment by Tastypotato245** [comment]
땡겼어 굿

**Comment by Tastypotato245** [comment]
받아오는 것 까지 성공하였음.

이제 업로드 하면 파이어베이스 user의 필드에 list로 doc ref가 추가되는지 확인해야함

![Image](https://github.com/cau-bootcamp/wehavit/assets/63251068/ab2b25b9-b2fd-4ce1-9de4-6a4dc9e98106)
