### ISSUE TITLE
[S17] 친구에 관한 모델 작성하기

### ISSUE THREAD

**Issue by sm-amoled** [cau-bootcamp/wehavit#38]
## Task
**User Story**: #19

### 설명
친구 엔티티 관리를 위한 모델 구조를 작성해야함 - 이후 프로젝트 확장성 고려가 필요함.
친구 관계에 관한 모델이 필요함

**Comment by Tastypotato245** [comment]
![Image](https://github.com/cau-bootcamp/wehavit/assets/63251068/3b2dbaa7-0491-480a-b5db-7b36fadb7ce9)

**Comment by IamGroooooot** [comment]
friends
 - id
 - friendName
 - imageUrl

@Tastypotato245 friend는 이렇게 된다는 것 맞나요?

그리고 Firebase 쪽에서는 user document 아래의 friends라는 컬렌션을 만들겠다는 건가요?

**Comment by Tastypotato245** [comment]
Firebase 쪽에서 userdoc 아래이 friends라는 컬렉션을 만드는 것 까지는 맞으나, 해당 컬렉션 내부의 docs의 id는 users에서의 user들의 docs id이기에, friends 컬렉션 아래의 docs는 아무런 필드를 가지지 않게 설계해보려고 했습니다

Android용 Outlook<https://aka.ms/AAb9ysg> 다운로드
________________________________
