### ISSUE TITLE
Git branch 전략에 관한 고민

### ISSUE THREAD

**Issue by IamGroooooot** [cau-bootcamp/wehavit#43]
Task 단위로 dev에서 branch를 파서 issue를 해결하자

스프린트가 끝날 때 Main Merge

**Comment by sm-amoled** [comment]
# 깃허브 브랜치 전략

## 브랜치

- 개발의 중심축이 되는 Branch는 `develop`이다.
- 모든 기능 개발 Branch는 `develop` 이하에서 파생되어 만들어진다
- develop 이하에서 만들어진 Branch의 이름은 `{이슈작업태그}/{작업번호}`의 규칙을 따른다.
    - ex) feat/#00
- 작업을 마친 Branch는 Merge 후 **PR 올린 사람**이 삭제한다.

## 커밋

💡 [#이슈번호] 작업 태그: 작업 내용
- ex) [#00] feat: aa 관련 기능 구현
- ex) [#43] docs: 깃허브 컨벤션 관련 문서 정리
이렇게 이슈 링크가 한 번에 돼서 관리가 편리해짐!

| Issue & Commit 작업태그 | 설명 |
| --- | --- |
| feat: | 새로운 기능 추가, UI 컴포넌트 추가 |
| fix: | 버그 수정 또는 typo |
| refactor: | 리팩토링 |
| design: | 사용자 UI 디자인 변경 (UI만 수정) |
| comment: | 필요한 주석 추가 및 변경 |
| style: | 코드 포맷팅, 세미콜론 누락, 코드 의미에 영향을 주지 않는 변경사항 |
| test: | 테스트(테스트 코드 추가, 수정, 삭제, 비즈니스 로직에 변경이 없는 경우) |
| chore: | 위에 걸리지 않는 기타 변경사항(빌드 스크립트 수정, assets image, 패키지 매니저 등) |
| rename: | 파일 혹은 폴더명 수정하거나 옮기는 경우 |
| remove: | 파일을 삭제하는 작업만 수행하는 경우 |

## 풀 리퀘스트

💡 [#이슈번호] 관련 이슈 작업 태그 - 작업 내용 축약

- **PR 작성 시 Label 설정**
    - `작업 담당자`, `작업 태그` 설정
    
    ```
    ###작업 내용 설명1. ~~를 작업
    2. ~~를 작업
    3. ~~를 작업
    
    ###관련 이슈- #이슈번호
    
    ###작업의 결과물- 코드 or 스크린샷 or 동영상
    - 작업의 결과물이 따로 존재하지 않는 경우에는 기록 X
    
    ###작업의 비고사항 및 한계점- 비고사항 및 한계점이 없다면 기록 X
    
    ###To Reviewers- 리뷰어에게 중점적으로 살펴봐줬으면 하는 내용
    
    Close #이슈번호
    ```
    
- 관련된 이슈가 PR Merge와 함께 닫혀야하는 경우 PR의 말미에 `Close #이슈번호` 를 작성한다.

**Comment by IamGroooooot** [comment]
lgtm!
