### ISSUE TITLE
[dev] 간단 뷰 용어 정리

### ISSUE THREAD

**Issue by Tastypotato245** [cau-bootcamp/wehavit#44]
중요한 뷰들 용어 정리

요건
- 길지 않고 명확히 구분이 되어야 함

**Comment by Tastypotato245** [comment]
https://www.notion.so/groot-coding/94ae5946277746e2b61aafd017a4269b?pvs=4

이곳에 정리됨

**Comment by IamGroooooot** [comment]
고마워~~!

**Comment by sm-amoled** [comment]
@Tastypotato245 목표별 통계 뷰는 GoalAnalyView보다 GoalStatView는 어떤 것 같아?

**Comment by Tastypotato245** [comment]
> @Tastypotato245 목표별 통계 뷰는 GoalAnalyView보다 GoalStatView는 어떤 것 같아?

좋아 이름 더 좋은 아이디어 있으면 더 내줘잉
