### ISSUE TITLE
임시 : 고정 시간 정하기

### ISSUE THREAD

**Issue by Tastypotato245** [cau-bootcamp/wehavit#49]
### 시간 정하기

실시간 글을 작성하는 시간을 고정하기로 하였는데, 언제가 좋을 지 근거를 제시, 설문 등을 돌려서 하나의 시간으로 고정할 것.

**Comment by Tastypotato245** [comment]
https://forms.gle/3KnTP5GuxpG9TyJU6

구글폼

**Comment by Tastypotato245** [comment]
설문 기간 11월 2일 (목) 오전 9시 ~ 11월 5일 (일) 오후 8시 약 4일 간

**Comment by IamGroooooot** [comment]
이메일은 필수 정보로 미포함해도 되지 않을까용?

**Comment by Tastypotato245** [comment]
이메일 설정이 기본값이라 인지를 못했쪄요 감사합니다

**Comment by IamGroooooot** [comment]
L굳!!TM
수고했어영

**Comment by Tastypotato245** [comment]
10시 fix
