### ISSUE TITLE
[S17] 파이어베이스에 친구 문서 ref 업로드

### ISSUE THREAD

**Issue by Tastypotato245** [cau-bootcamp/wehavit#72]

**Comment by Tastypotato245** [comment]
![Image](https://github.com/cau-bootcamp/wehavit/assets/63251068/48ca1bd4-b1f3-4236-ae39-6bfa80e317e2)

올라가는 건 되는데 해당 문서 가 존재하는지 아닌지 검색해서 있으면 정상적으로 추가하도록 해야함.

**Comment by Tastypotato245** [comment]
![Image](https://github.com/cau-bootcamp/wehavit/assets/63251068/3e5143b2-eea7-4a55-b120-5790a400f489)



![Image](https://github.com/cau-bootcamp/wehavit/assets/63251068/19cf9d10-c401-457c-89aa-1a19652c41b6)


뭔가 여기까지 String 데이터가 안넘어와서, 내일 확인해볼 예정

**Comment by Tastypotato245** [comment]
이게 계속 안되어서 고민중 스크럼 때 잠시 봐주세욥

**Comment by IamGroooooot** [comment]
무슨 브랜치야?
안 되는 string은 AddFriendModel의 friendId?

**Comment by Tastypotato245** [comment]
오늘 배운 것
1. dart analysis에 lint 안맞는 것들이 뜬다. 수정하자.
2. 포맷팅 (shift shift-> save on ~ -> reformat) command + s 하면서 하자.
3. provider의 autodispose : 단순히 ref.read하고 있는 상태에서, 위젯을 다시 그릴 때 hold하고 있는 (변수 또는 watch하고 있는) 구문이 없으면 autodispose가 불리며 state가 계속 날아가니, ref watch를 넣어주거나, 또는 state가 필요한 경우 state를 만들어서 그것을 넘겨주는 등, 위젯 내에서 state가 어떤 상태로 유지되어야 하는지를 명시하여야 한다. 그렇지 않으면 계속 autodispose가 불리며 날아감.

keep alive 라는 것도 있지만, 해당 방식 보다는 autodispose가 필요한 상황에만 잘 불리도록 다르게 처리하는 것이 나아 보인다.

많이 배웠습니다.
