### ISSUE TITLE
[S12] 메인 뷰를 위젯 단위로 나누기

### ISSUE THREAD

**Issue by Tastypotato245** [cau-bootcamp/wehavit#81]
To do

- [x] 오늘 날짜 표시
- [x] feedBlockWidget분리
- [x] 게시글 모델 작성(?) 이미 있는 것 디벨롭
- [x] 일단은 최근 30일을 스크롤하여 선택할 수 있는 아이템 리스트 만들기
- [x] 디폴트 값 : 가장 최근 게시된 날짜 : 근데 이제 실시간 시간 전에는 전날꺼, 이후에는 만약 작성을 했다면 노출, 아니면 비노출
- [x] 일자 선택 시 해당 일자에 맞는 게시글 불러오기
- [x] 게시글 피드 구성하기 위젯으로

**Comment by Tastypotato245** [comment]
안되는 점
1. 뷰 최초 접속 시 state 초기화
 -> consumer stateful widget 공부

2. 1번이 해결되면 곧바로
 a. 뷰 들어갈 시 마지막 인덱스로 초기화 (init state)
 b. 그에 맞는 feed list도 보여지게.

3. 이후 게시글 위젯 나누고~~ 등등

**Comment by sm-amoled** [comment]
`initState` 또는 `didChangeDependencies` 에서 함수를 호출해보세요
